name: FloorPaint
version: 1.0
main: com.popupmc.floorpaint.FloorPaint
description: Floor Paint
author: junebug12851
api-version: 1.15
depend: [Multiverse-Core]

commands:
  paint-color:
    description: Change Paint Color
    usage: /paint-color black|blue|green|brown|red|purple|orange|random|none
